### ISSUE TITLE
I got error when devploy reaction comerce to heroku

### ISSUE THREAD

**Issue by 2pay** [reactioncommerce/reaction-docs#177]
I have followed the instruction steps in: 
`https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-heroku`

But i got error:

`An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.`

This is logs on heroku:

```
/app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:280
2017-04-08T02:37:59.418895+00:00 app[web.1]:                                            throw(ex);
2017-04-08T02:37:59.418897+00:00 app[web.1]:                                            ^
2017-04-08T02:37:59.418898+00:00 app[web.1]:
2017-04-08T02:37:59.418899+00:00 app[web.1]: Error: Address must be a valid e-mail address
2017-04-08T02:37:59.418900+00:00 app[web.1]:     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
2017-04-08T02:37:59.418901+00:00 app[web.1]:     at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
2017-04-08T02:37:59.418902+00:00 app[web.1]:     at [object Object].Mongo.Collection.(anonymous function) (packages/aldeed_collection2-core.
js:214:25)
2017-04-08T02:37:59.418904+00:00 app[web.1]:     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run
-as-user.js:325:19)
2017-04-08T02:37:59.418905+00:00 app[web.1]:     at Object.module.export.exports.default.createDefaultAdminUser (server/api/core/core.js:292
:11)
2017-04-08T02:37:59.418906+00:00 app[web.1]:     at Object.module.export.exports.default.init (server/api/core/core.js:34:10)
2017-04-08T02:37:59.418907+00:00 app[web.1]:     at module.export.exports.default (server/startup/init.js:8:12)
2017-04-08T02:37:59.418908+00:00 app[web.1]:     at module.export.exports.default (server/startup/index.js:18:3)
2017-04-08T02:37:59.418909+00:00 app[web.1]:     at server/main.js:6:3
2017-04-08T02:37:59.418909+00:00 app[web.1]:     at Function.time (/app/.meteor/heroku_build/app/programs/server/profile.js:309:28)
2017-04-08T02:37:59.418910+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:312:13
2017-04-08T02:37:59.418911+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:353:5
2017-04-08T02:37:59.418912+00:00 app[web.1]:     at Function.run (/app/.meteor/heroku_build/app/programs/server/profile.js:510:12)
2017-04-08T02:37:59.418912+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:351:11
2017-04-08T02:37:59.603255+00:00 heroku[web.1]: Process exited with status 1
2017-04-08T02:37:59.630433+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by zenweasel** [comment]
We don't support deployment to Heroku, the instructions in the docs are community contributed (and over 2 years old) so you might want to take a look at: https://medium.com/@oreagunbiade/reactioncommerce-heroku-deploy-guide-f5672e242863

**Comment by zenweasel** [comment]
Heroku docs have been removed.
